name: Update issue, pr and contrib metadata file for current year

on:
  workflow_dispatch:
  schedule:
    # Runs on the 1 and 15 of each month at 00:00 UTC (see https://crontab.guru)
    - cron: "0 5 2,16 * 1"
    # Runs at 11pm on December 31st every year
    - cron: "0 23 31 12 *"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-meta:
    if: github.repository_owner == 'pyopensci'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python -m pip install --upgrade pip wheel
      - name: Install webp
        run: |
          sudo apt-get update
          sudo apt-get install -y webp
      - name: Install pyosmeta
        run: pip install -r requirements.txt
      - name: Run get-prs
        run: python scripts/get-prs.py
      - name: Run get-reviews
        run: python scripts/get-reviews.py
      - name: Run get-sprint-data
        run: python scripts/get-sprint-data.py
      - name: get-review-contributors
        run: python scripts/get-review-contributors.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            _data/*.csv
          author: Leah <leah@pyopensci.org>
          base: main
          branch: contribs
          commit-message: "Update: issue, pr and contrib metadata file for current year"
          delete-branch: true
          title: Update contributor and review data
        env:
          # Custom token needed to trigger PR checks, as GITHUB_TOKEN won't
          # https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
          GITHUB_TOKEN: ${{ secrets.PYOS_PR_TOKEN }}
